/** 
 *  Array contenant l'ensemble des données necessaires pour notre application jeux de mot
 */
var data = [
    {
        "categorie":"fruits",
        "libelle": "POMME",
        "img":"../res/img/fruits/pomme.png",
        "audio":"./res/audio/fruits/Fr-pomme.ogg",
        "lettres": [ 
            {
                "libelle":"P",
                "audio":"./res/audio/lettres/Fr-P.ogg" 
            },
            {
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
            {
                "libelle":"M",
                "audio":"./res/audio/lettres/Fr-M.ogg" 
            },
            {
                "libelle":"M",
                "audio":"./res/audio/lettres/Fr-M.ogg" 
            },
            {
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            }
        ]
    },
    {
        "categorie":"fruits",
        "libelle": "POIRE",
        "img":"../res/img/fruits/poire.png",
        "audio":"./res/audio/fruits/Fr-poire.ogg",
		"lettres": [ 
            {
                "libelle":"P",
                "audio":"./res/audio/lettres/Fr-P.ogg" 
            },
            {
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
            {
                "libelle":"I",
                "audio":"./res/audio/lettres/Fr-I.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
            {
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            }
        ]
    },
    {
        "categorie":"fruits",
        "libelle": "ORANGE",
        "img":"../res/img/fruits/orange.png",
        "audio":"./res/audio/fruits/Fr-orange.ogg",
		"lettres": [ 
            {
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
            {
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            },
            {
                "libelle":"G",
                "audio":"./res/audio/lettres/Fr-G.ogg" 
            },
			{
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            }
        ]
    },
    {
        "categorie":"fruits",
        "libelle": "TOMATE",
        "img":"../res/img/fruits/tomate.png",
        "audio":"./res/audio/fruits/Fr-tomate.ogg",
		"lettres": [ 
            {
                "libelle":"T",
                "audio":"./res/audio/lettres/Fr-T.ogg" 
            },
            {
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
            {
                "libelle":"M",
                "audio":"./res/audio/lettres/Fr-M.ogg" 
            },
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
            {
                "libelle":"T",
                "audio":"./res/audio/lettres/Fr-T.ogg" 
            },
			{
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            }
        ]
    },
    {
        "categorie":"fruits",
        "libelle": "NOISETTE",
        "img":"../res/img/fruits/noisette.png",
        "audio":"./res/audio/fruits/Fr-noisette.ogg",
		"lettres": [ 
            {
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            },
            {
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
            {
                "libelle":"I",
                "audio":"./res/audio/lettres/Fr-I.ogg" 
            },
            {
                "libelle":"S",
                "audio":"./res/audio/lettres/Fr-S.ogg" 
            },
            {
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            },
			{
                "libelle":"T",
                "audio":"./res/audio/lettres/Fr-T.ogg" 
            },
			{
                "libelle":"T",
                "audio":"./res/audio/lettres/Fr-T.ogg" 
            },
			{
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            }
        ]
    },
    {
        "categorie":"fruits",
        "libelle": "FRAISE",
        "img":"../res/img/fruits/fraise.png",
        "audio":"./res/audio/fruits/Fr-fraise.ogg",
		"lettres": [ 
            {
                "libelle":"F",
                "audio":"./res/audio/lettres/Fr-F.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
            {
                "libelle":"I",
                "audio":"./res/audio/lettres/Fr-I.ogg" 
            },
            {
                "libelle":"S",
                "audio":"./res/audio/lettres/Fr-S.ogg" 
            },
			{
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            }
        ]
    },
    {
        "categorie":"fruits",
        "libelle": "ABRICOT",
        "img":"../res/img/fruits/abricot.png",
        "audio":"./res/audio/fruits/Fr-abricot.ogg",
		"lettres": [ 
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
            {
                "libelle":"B",
                "audio":"./res/audio/lettres/Fr-B.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
            {
                "libelle":"I",
                "audio":"./res/audio/lettres/Fr-I.ogg" 
            },
            {
                "libelle":"C",
                "audio":"./res/audio/lettres/Fr-C.ogg" 
            },
			{
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
			{
                "libelle":"T",
                "audio":"./res/audio/lettres/Fr-T.ogg" 
            }
        ]
    },
    {
        "categorie":"fruits",
        "libelle": "CITRON",
        "img":"../res/img/fruits/citron.png",
        "audio":"./res/audio/fruits/Fr-citron.ogg",
		"lettres": [ 
            {
                "libelle":"C",
                "audio":"./res/audio/lettres/Fr-C.ogg" 
            },
            {
                "libelle":"I",
                "audio":"./res/audio/lettres/Fr-I.ogg" 
            },
            {
                "libelle":"T",
                "audio":"./res/audio/lettres/Fr-T.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
            {
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
			{
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            }
        ]
    },
    {
        "categorie":"fruits",
        "libelle": "ANANAS",
        "img":"../res/img/fruits/ananas.png",
        "audio":"./res/audio/fruits/Fr-ananas.ogg",
		"lettres": [ 
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
            {
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            },
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
            {
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            },
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
			{
                "libelle":"S",
                "audio":"./res/audio/lettres/Fr-S.ogg" 
            }
        ]
    },
    {
        "categorie":"fruits",
        "libelle": "PECHE",
        "img":"../res/img/fruits/peche.png",
        "audio":"./res/audio/fruits/Fr-peche.ogg",
		"lettres": [ 
            {
                "libelle":"P",
                "audio":"./res/audio/lettres/Fr-P.ogg" 
            },
            {
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            },
            {
                "libelle":"C",
                "audio":"./res/audio/lettres/Fr-C.ogg" 
            },
            {
                "libelle":"H",
                "audio":"./res/audio/lettres/Fr-H.ogg" 
            },
            {
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            }
        ]
    },
    {
        "categorie":"animaux",
        "libelle": "CHEVAL",
        "img":"../res/img/animaux/cheval.png",
        "audio":"./res/audio/animaux/Fr-cheval.ogg",
		"lettres": [ 
            {
                "libelle":"C",
                "audio":"./res/audio/lettres/Fr-C.ogg" 
            },
            {
                "libelle":"H",
                "audio":"./res/audio/lettres/Fr-H.ogg" 
            },
            {
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            },
            {
                "libelle":"V",
                "audio":"./res/audio/lettres/Fr-V.ogg" 
            },
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
			{
                "libelle":"L",
                "audio":"./res/audio/lettres/Fr-L.ogg" 
            }
        ]
    },
    {
        "categorie":"animaux",
        "libelle": "CHIEN",
        "img":"../res/img/animaux/chien.png",
        "audio":"./res/audio/animaux/Fr-chien.ogg",
		"lettres": [ 
            {
                "libelle":"C",
                "audio":"./res/audio/lettres/Fr-C.ogg" 
            },
            {
                "libelle":"H",
                "audio":"./res/audio/lettres/Fr-H.ogg" 
            },
            {
                "libelle":"I",
                "audio":"./res/audio/lettres/Fr-I.ogg" 
            },
            {
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            },
            {
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            }
        ]
    },
    {
        "categorie":"animaux",
        "libelle": "CHAT",
        "img":"../res/img/animaux/chat.png",
        "audio":"./res/audio/animaux/Fr-chat.ogg",
		"lettres": [ 
            {
                "libelle":"C",
                "audio":"./res/audio/lettres/Fr-C.ogg" 
            },
            {
                "libelle":"H",
                "audio":"./res/audio/lettres/Fr-H.ogg" 
            },
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
            {
                "libelle":"T",
                "audio":"./res/audio/lettres/Fr-T.ogg" 
            }
        ]
    },
    {
        "categorie":"animaux",
        "libelle": "POISSON",
        "img":"../res/img/animaux/poisson.png",
        "audio":"./res/audio/animaux/Fr-poisson.ogg",
		"lettres": [ 
            {
                "libelle":"P",
                "audio":"./res/audio/lettres/Fr-P.ogg" 
            },
            {
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
            {
                "libelle":"I",
                "audio":"./res/audio/lettres/Fr-I.ogg" 
            },
            {
                "libelle":"S",
                "audio":"./res/audio/lettres/Fr-S.ogg" 
            },
			{
                "libelle":"S",
                "audio":"./res/audio/lettres/Fr-S.ogg" 
            },
			{
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
			{
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            }
        ]
    },
    {
        "categorie":"animaux",
        "libelle": "COCHON",
        "img":"../res/img/animaux/cochon.png",
        "audio":"./res/audio/animaux/Fr-cochon.ogg",
		"lettres": [ 
            {
                "libelle":"C",
                "audio":"./res/audio/lettres/Fr-C.ogg" 
            },
            {
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
            {
                "libelle":"C",
                "audio":"./res/audio/lettres/Fr-C.ogg" 
            },
            {
                "libelle":"H",
                "audio":"./res/audio/lettres/Fr-H.ogg" 
            },
			{
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
			{
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            }
        ]
    },
    {
        "categorie":"animaux",
        "libelle": "VACHE",
        "img":"../res/img/animaux/vache.png",
        "audio":"./res/audio/animaux/Fr-vache.ogg",
		"lettres": [ 
            {
                "libelle":"V",
                "audio":"./res/audio/lettres/Fr-V.ogg" 
            },
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
            {
                "libelle":"C",
                "audio":"./res/audio/lettres/Fr-C.ogg" 
            },
            {
                "libelle":"H",
                "audio":"./res/audio/lettres/Fr-H.ogg" 
            },
			{
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            }
        ]
    },
    {
        "categorie":"animaux",
        "libelle": "MOUTON",
        "img":"../res/img/animaux/mouton.png",
        "audio":"./res/audio/animaux/Fr-mouton.ogg",
		"lettres": [ 
            {
                "libelle":"M",
                "audio":"./res/audio/lettres/Fr-M.ogg" 
            },
            {
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
            {
                "libelle":"U",
                "audio":"./res/audio/lettres/Fr-U.ogg" 
            },
            {
                "libelle":"T",
                "audio":"./res/audio/lettres/Fr-T.ogg" 
            },
			{
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
			{
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            }
        ]
    },
    {
        "categorie":"animaux",
        "libelle": "PERROQUET",
        "img":"../res/img/animaux/perroquet.png",
        "audio":"./res/audio/animaux/Fr-perroquet.ogg",
		"lettres": [ 
            {
                "libelle":"P",
                "audio":"./res/audio/lettres/Fr-P.ogg" 
            },
            {
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
			{
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
			{
                "libelle":"Q",
                "audio":"./res/audio/lettres/Fr-Q.ogg" 
            },
			{
                "libelle":"U",
                "audio":"./res/audio/lettres/Fr-U.ogg" 
            },
			{
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            },
			{
                "libelle":"T",
                "audio":"./res/audio/lettres/Fr-T.ogg" 
            }
        ]
    },
    {
        "categorie":"animaux",
        "libelle": "SINGE",
        "img":"../res/img/animaux/singe.png",
        "audio":"./res/audio/animaux/Fr-singe.ogg",
		"lettres": [ 
            {
                "libelle":"S",
                "audio":"./res/audio/lettres/Fr-S.ogg" 
            },
            {
                "libelle":"I",
                "audio":"./res/audio/lettres/Fr-I.ogg" 
            },
            {
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            },
            {
                "libelle":"G",
                "audio":"./res/audio/lettres/Fr-G.ogg" 
            },
			{
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            }
        ]
    },
    {
        "categorie":"animaux",
        "libelle": "GIRAFE",
        "img":"../res/img/animaux/girafe.png",
        "audio":"./res/audio/animaux/Fr-girafe.ogg",
		"lettres": [ 
            {
                "libelle":"G",
                "audio":"./res/audio/lettres/Fr-G.ogg" 
            },
            {
                "libelle":"I",
                "audio":"./res/audio/lettres/Fr-I.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
			{
                "libelle":"F",
                "audio":"./res/audio/lettres/Fr-F.ogg" 
            },
			{
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            }
        ]
    },
    {
        "categorie":"couleurs",
        "libelle": "ORANGE",
        "img":"../res/img/couleurs/orange.png",
        "audio":"./res/audio/couleurs/Fr-orange.ogg",
		"lettres": [ 
            {
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
            {
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            },
			{
                "libelle":"G",
                "audio":"./res/audio/lettres/Fr-G.ogg" 
            },
			{
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            }
        ]
    },
    {
        "categorie":"couleurs",
        "libelle": "BLEU",
        "img":"../res/img/couleurs/bleu.png",
        "audio":"./res/audio/couleurs/Fr-bleu.ogg",
		"lettres": [ 
            {
                "libelle":"B",
                "audio":"./res/audio/lettres/Fr-B.ogg" 
            },
            {
                "libelle":"L",
                "audio":"./res/audio/lettres/Fr-L.ogg" 
            },
            {
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            },
            {
                "libelle":"U",
                "audio":"./res/audio/lettres/Fr-U.ogg" 
            }
        ]
    },
    {
        "categorie":"couleurs",
        "libelle": "ROUGE",
        "img":"../res/img/couleurs/rouge.png",
        "audio":"./res/audio/couleurs/Fr-rouge.ogg",
		"lettres": [ 
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
            {
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
            {
                "libelle":"U",
                "audio":"./res/audio/lettres/Fr-U.ogg" 
            },
            {
                "libelle":"G",
                "audio":"./res/audio/lettres/Fr-G.ogg" 
            },
			{
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            }
        ]
    },
    {
        "categorie":"couleurs",
        "libelle": "JAUNE",
        "img":"../res/img/couleurs/jaune.png",
        "audio":"./res/audio/couleurs/Fr-jaune.ogg",
		"lettres": [ 
            {
                "libelle":"J",
                "audio":"./res/audio/lettres/Fr-J.ogg" 
            },
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
            {
                "libelle":"U",
                "audio":"./res/audio/lettres/Fr-U.ogg" 
            },
            {
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            },
			{
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            }
        ]
    },
    {
        "categorie":"couleurs",
        "libelle": "MARRON",
        "img":"../res/img/couleurs/marron.png",
        "audio":"./res/audio/couleurs/Fr-marron.ogg",
		"lettres": [ 
            {
                "libelle":"M",
                "audio":"./res/audio/lettres/Fr-M.ogg" 
            },
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
			{
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
			{
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            }
        ]
    },
    {
        "categorie":"couleurs",
        "libelle": "GRIS",
        "img":"../res/img/couleurs/gris.png",
        "audio":"./res/audio/couleurs/Fr-gris.ogg",
		"lettres": [ 
            {
                "libelle":"G",
                "audio":"./res/audio/lettres/Fr-G.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
            {
                "libelle":"I",
                "audio":"./res/audio/lettres/Fr-I.ogg" 
            },
            {
                "libelle":"S",
                "audio":"./res/audio/lettres/Fr-S.ogg" 
            }
        ]
    },
    {
        "categorie":"couleurs",
        "libelle": "VIOLET",
        "img":"../res/img/couleurs/violet.png",
        "audio":"./res/audio/couleurs/Fr-violet.ogg",
		"lettres": [ 
            {
                "libelle":"V",
                "audio":"./res/audio/lettres/Fr-V.ogg" 
            },
            {
                "libelle":"I",
                "audio":"./res/audio/lettres/Fr-I.ogg" 
            },
            {
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
            {
                "libelle":"L",
                "audio":"./res/audio/lettres/Fr-L.ogg" 
            },
			{
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            },
			{
                "libelle":"T",
                "audio":"./res/audio/lettres/Fr-T.ogg" 
            }
        ]
    },
    {
        "categorie":"couleurs",
        "libelle": "BLANC",
        "img":"../res/img/couleurs/blanc.png",
        "audio":"./res/audio/couleurs/Fr-blanc.ogg",
		"lettres": [ 
            {
                "libelle":"B",
                "audio":"./res/audio/lettres/Fr-B.ogg" 
            },
            {
                "libelle":"L",
                "audio":"./res/audio/lettres/Fr-L.ogg" 
            },
            {
                "libelle":"A",
                "audio":"./res/audio/lettres/Fr-A.ogg" 
            },
            {
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            },
			{
                "libelle":"C",
                "audio":"./res/audio/lettres/Fr-C.ogg" 
            }
        ]
    },
    {
        "categorie":"couleurs",
        "libelle": "NOIR",
        "img":"../res/img/couleurs/noir.png",
        "audio":"./res/audio/couleurs/Fr-noir.ogg",
		"lettres": [ 
            {
                "libelle":"N",
                "audio":"./res/audio/lettres/Fr-N.ogg" 
            },
            {
                "libelle":"O",
                "audio":"./res/audio/lettres/Fr-O.ogg" 
            },
            {
                "libelle":"I",
                "audio":"./res/audio/lettres/Fr-I.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            }
        ]
    },
    {
        "categorie":"couleurs",
        "libelle": "VERT",
        "img":"../res/img/couleurs/vert.png",
        "audio":"./res/audio/couleurs/Fr-vert.ogg",
		"lettres": [ 
            {
                "libelle":"V",
                "audio":"./res/audio/lettres/Fr-V.ogg" 
            },
            {
                "libelle":"E",
                "audio":"./res/audio/lettres/Fr-E.ogg" 
            },
            {
                "libelle":"R",
                "audio":"./res/audio/lettres/Fr-R.ogg" 
            },
            {
                "libelle":"T",
                "audio":"./res/audio/lettres/Fr-T.ogg" 
            }
        ]
    }
]

